### ISSUE TITLE
[PROBLEM] server only works in teenversion!

### ISSUE THREAD

**Issue by xDezossAx** [opendarkeden/server#34]
HI @tiancaiamao , I noticed that in the options even unchecking teen version, when you enter the map it is in teen version (no blood when attacking monsters, monster bodies turn ashes, heads in the shape of crystals, as shown in the attached image), I even thought it would be the client , but even using the others, it is the same way.

So I think it's something in the server files, I realized it must be related to the CHILD flag (children) but I can't analyze the files like you, can you notice something?

![teenversion-flag-child](https://user-images.githubusercontent.com/51914495/128641537-0bbf5575-659f-4302-a4f6-0b8aa2b7f6e4.png)

**Comment by tiancaiamao** [comment]
I didn't notice if before...
I need to take a look.

**Comment by xDezossAx** [comment]
It's strange @, when you run as an administrator on Windows 10, it opens the game, it shows that teenversion is checked in the game option, you uncheck it, but when you enter the game it checks again, I have another file here that was in teen version too , but unchecking the login screen, I managed to enter the map and it worked normally. kind of weird this error.

**Comment by tiancaiamao** [comment]
Fixed in https://github.com/opendarkeden/client/pull/15

Yes, the server send a packet to ask the client to display teen version.

https://github.com/opendarkeden/server/blob/e4f695fa223f7d3160dceb2c99d10ec43aacc2e4/src/Core/CLLoginHandler.cpp#L566-L606

It's check depend on the SSN value in the database...  checking the birthday and age of the player information.
I just modify the client to ignore this setting.

**Comment by xDezossAx** [comment]
Great idea @tiancaiamao, thanks for the solution, congratulations! :)
