### ISSUE TITLE
Which IP address do I use to connect?

### ISSUE THREAD

**Issue by rafakave** [opendarkeden/server#37]
I'm using Docker with WSL.

Which IP should I put in ServerInfo.inf to connect to the server?
Isn't it the IP of the WSL adapter?
Is it localhost? 127.0.0.1?

If I use WSL's adapter IP, the client abruptly closes.

![wsl-adapter](https://user-images.githubusercontent.com/16522342/131754159-a1730e6d-00d6-4f75-b479-04d827cd4726.png)

**Comment by tiancaiamao** [comment]
When you're using docker, connect `127.0.0.1`
Change the `Data/Info/GameClient.inf` file like this:

```
MaxLoginServerAddress : 1
LoginServerAddress : 127.0.0.1
LoginServerPortNum : 1
LoginServerPort : 9999
LoginServerCheckPort : 9997
LoginServerBasePort : 9900
```

**Comment by tiancaiamao** [comment]
Tips:   1. The file type should be unix, instead of dos

That means the newline should be `\n` instead of `\r\n`
If you're using vim, use this command to make sure it's unix:

```
:set ff=unix
```


2. You have to use this game client, because some other client forbid connecting to `127.0.0.1`, the restriction is removed in this client.  See https://github.com/opendarkeden/client/pull/14

**Comment by tiancaiamao** [comment]
Oh, I find the problem. @rafakave 

You should change the `GameClient.inf` file, instead of `ServerInfo.inf`


See here:

https://github.com/opendarkeden/client/blob/78db63d23b4fcb937eac650486d28988641d1546/Client/GameInit.cpp#L1865-L1889

`FILE_INFO_GAMECLIENT2` is actually used, rather than `FILE_INFO_SERVERINFO`


And from `FileDef.inf`, you can see

`FILE_INFO_GAMECLIENT2` is `GameClient.inf`
`FILE_INFO_SERVERINFO` is `ServerInfo.inf`

Though this is misleading somehow.

**Comment by rafakave** [comment]
Thanks, I'll test it right now.

**Comment by tiancaiamao** [comment]
Just now, I fixed a bug https://github.com/opendarkeden/server/pull/39
But if the IP is `127.0.0.1`, the bug should have no affect.


**Before the bug is fixed, it's impossible to depoly the client and the server in different computer using the docker way.**  (using real linux is available)

After the fix, if someone want to make the server and the client in different computer, he should change the `GameServerInfo` table to the server IP (not `127.0.0.1`), and modify the `GameClient.inf` to use that IP.

Login to the mysql using this command:

```
docker exec -it docker_odk-mysql_1 mysql -u root -p

123456
```

**Comment by rafakave** [comment]
Can't use a different client?

**Comment by tiancaiamao** [comment]
> Can't use a different client?

Some other clients could work, if its version match the server source code.

**Comment by rafakave** [comment]
Ok, with the compiled client I managed to connect.
